#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Instruction {
    PushStack(i32),
    DuplicateStack,
    CopyNthStack(i32),
    SwapStack,
    DiscardStack,
    SlideNStack(i32),
    Add,
    Subtract,
    Multiply,
    IntegerDivision,
    Modulo,
    StoreHeap,
    RetrieveHeap,
    Mark(i32),
    Call(i32),
    Jump(i32),
    JumpZero(i32),
    JumpNegative(i32),
    Return,
    Exit,
    OutCharacter,
    OutInteger,
    ReadCharacter,
    ReadInteger,
}
